### ISSUE TITLE
Installing an Image to ARM Target ends blinking LED

### ISSUE THREAD

**Issue by martiinz** [ni/nilrt#10]
Refering to the [19.1 Branch README](https://github.com/ni/nilrt/blob/nilrt/19.1/README.md)

I've successully built the "niconsole-image". Trying to install the rootfs ends up with a continuous blinking Status LED. Therefore a few questions to following section

> ## Installing a Complete Image to an RT Target
> 
> 1. Boot the target into safe mode. Refer to your hardware's manual for details on booting to safe mode.
> 
> 2. If you are using a custom kernel, backup the NI-built kernel and modules.
> 
> ```bash
> /boot/linux_runmode.itb  # kernel location on ARM targets
> /lib/modules/            # kernel modules
> ```
> [...]
> 
> 5. Restore the NI-built kernel and module to their original locations in
>   ``/boot`` and ``/lib/modules/`` **or** install your custom-built kernel as
>    described in ``KERNEL_SOURCE.md``.
> ### Logging In
> 
> NI's additions to the base image include scripts and other software affecting login. To enable login without NI software, you will need to make a few more changes. Assuming you are in safe mode and the run mode filesystem is mounted at /mnt/userfs:

**To Point 2:**
 a)  only if when using custom kernel, or anyway?
 b) and are the paths correct when running in safe mode or do I need to backup those in `/mnt/userfs`

3 and 4 looks pretty clear

**To Point 5:**
same than 2b) 

**To Logging In**
The NI Software, is the one installed by `/usr/local/natinst/tools/versioning_utils.sh` and `/usr/local/natinst/nikal/bin/updateNIDrivers` as decribed in [Kernel Source](https://github.com/ni/nilrt/blob/nilrt/19.1/KERNEL_SOURCE.md#compiling-the-kernel)?

Thanks

PS: Running a custom Kernel runs fine. [Brad's Videos](https://www.youtube.com/watch?v=pjRfKh8kf4o) are really helpful.

**Comment by bstreiff** [comment]
The status LED is controlled by a hardware circuit that will generate a blink pattern if software fails to indicate a successful boot within a certain period of time. The [status_led script](https://github.com/ni/meta-nilrt/blob/nilrt_pub/19.1/sumo/recipes-ni/ni-utils/files/status_led) is responsible for making that indication (and turning that LED off); typically it is invoked via `/etc/rc5.d/S98nivalidatestartup`.

As for your other questions:

- 2a: If you intend to use a custom kernel, you don't need to back up the NI-built one (this is for restoring it in step 5)
- 2b: I believe the guide is in error here-- when in safemode, to back up the runmode kernel's modules  you would want to collect `/mnt/userfs/lib/modules/`
- 5: same as 2b

I don't quite understand your last question. The steps in the README to "enable login without NI software" are present to initialize logins with the traditional `/etc/passwd` database (NI software would otherwise use a database unimaginatively called "NIAuth"). The `versioning_utils.sh` and `updateNIDrivers` steps that you reference are needed if you're trying to use NI driver software installed from MAX, as the out-of-tree kernel modules installed through that scheme would need to be versioned against your custom kernel instead of the NI-built kernel that they were installed with. Do those statements answer your question?

**Comment by martiinz** [comment]
ok cool, that makes sense. so it's
```bash 
/boot/linux_runmode.itb             # kernel location on ARM targets
/mnt/userfs/lib/modules/            # kernel modules
```
I'm still not there. MAX Status says "Safe Mode (Software Error)". 
I try to get the Serial Console Output to dig deeper...

**Comment by martiinz** [comment]
On the console, I am able to login. But the sbRIO misses /usr/local/natinst/bin/nirtcfg, see the full Output below.

I guess that meant by following statement in [readme](https://github.com/ni/nilrt/blob/nilrt/19.1/README.md)?
> NI's additions to the base image include scripts and other software [...]

So any way to complete the sbRIO, to have a full LabVIEW Target again?
Just copy the binaries? Install the software by MAX?

```
Booting LabVIEW RT...
INIT: version 2.88 booting
Starting udev
[    6.764304] ubi0 error: ubi_open_volume: cannot open device 0, volume 2, error -16
[    6.794947] ubi1 error: ubi_open_volume: cannot open device 1, volume 0, error -16
New system hostname: NI-sbRIO-9651-01dd1c2d
Missing file:/usr/lib/nisetbootmode.functions
Starting rtctld: done
Configuring packages on first boot....
 (This may take several minutes. Please do not power off the machine.)
update-rc.d: /etc/init.d/run-postinsts exists during rc.d purge (continuing)
 Removing any system startup links for run-postinsts ...
  /etc/rcS.d/S99run-postinsts
INIT: Entering runlevel: 5
Configuring network interfaces... done.
Starting system message bus: dbus.
/etc/rc5.d/S09sshd: line 24: /usr/local/natinst/bin/nirtcfg: No such file or directory
 * Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon
   ...done.
/etc/rc5.d/S90crond: line 27: /usr/local/natinst/bin/nirtcfg: No such file or directory
/etc/rc5.d/S90crond: line 27: [: too many arguments

NI Linux Real-Time 7.1 NI-sbRIO-9651-xxxxxxxxx ttyS0

NI-sbRIO-9651-xxxxxxxx login: root
```

**Comment by bstreiff** [comment]
Okay, I think I see what you're trying to do; unfortunately I don't think we provide all the pieces for you to be successful here.

The NI OpenEmbedded sources are worthwhile for building individual IPKs for adding to a target, but we do have parts of the system that utilize proprietary bits (such as the `nirtcfg` utility) that are added to the system at a later point in our internal build process. The OE sources we provide won't get you a complete, MAX-targetable image. It's probably possible to transplant the binaries out of the prior install made to that target, but I don't have an exhaustive doc on what files you'd need.

At this time, the expected path is to use MAX to provision the target (at this point, you'll probably have to head back into safemode to do so) with the desired version of NI Linux RT, then install your custom IPKs (or custom kernel) on top of that.

**Comment by martiinz** [comment]
Allright, so I will manually add the desired IPKs and my applications. 

An NI provided, puplic buildserver would be cool. Where I can do my OE settings and get the image some hours later :)

Thank you for the support anyway.
Cheers
