### ISSUE TITLE
ERROR: Nothing RPROVIDES 'grub-efi-nilrt' 

### ISSUE THREAD

**Issue by tonycc521** [ni/nilrt#262]
When I was compiling LinuxRT for arm, I went to readme step 7 and encountered the following error. How do I solve it?
![1](https://github.com/ni/nilrt/assets/47617106/839cac83-1061-44c1-9ca1-e9fe6e788458)

**Comment by amstewart** [comment]
I assume you're looking at the README from the `nilrt/24.0/sumo` branch. Unfortunately, these repos cannot be used to build images for NILRT ARM, because our ARM builds depend on components and infrastructure that are internal to NI. However, you can still use the OE repos to build your own packages and package feeds. So the useful parts of the README for ARM go through step 6.

I'll make a note to clarify those points in the ARM README.

**Comment by tonycc521** [comment]
How do I install LinuxRT on my arm?

**Comment by amstewart** [comment]
You can use NI MAX or Systemlink to connect to the device and install a system image that NI has built for that device. Those all should be available from the NI Package Manager - if you have that installed.
