### ISSUE TITLE
Missing libgflags

### ISSUE THREAD

**Issue by tonycc521** [ni/nilrt#264]
I installed NI LinuxRT on my hardware, but the lack of libgflags files caused my own wrapped so files can not be executed, copy these files to the usr/lib path, my so files can be executed normally, such as pictures
![miss](https://github.com/ni/nilrt/assets/47617106/a82c1c1c-a6e4-4758-8c47-c07f25a35a6f)

**Comment by amstewart** [comment]
Hey Tony.

Based on what I'm seeing, it looks like the `libgflags.2.*` SOs are getting packaged in the `gflags-dev` IPK. But the top-level `libgflags.so` symlink is in the `gflags` base IPK. I agree that doesn't make a whole lot of sense, and seems like an issue with how the `gflags.bb` recipe is constructed. Otherwise, all the library content looks to get installed to `/usr/lib` (correctly). So you may be able to workaround your issue simply by installing both `gflags` and `gflags-dev`.

The [glfags](https://github.com/ni/meta-openembedded/blob/3139ffbe88cbe85d390d3b0769ca4e3fefc8c4de/meta-oe/recipes-support/gflags/gflags_2.2.2.bb) recipe is being built as a part of our [extra/ package feeds](http://download.ni.com/#ni-linux-rt/feeds/2024Q1/x64/extra/core2-64/). Per our [package feed policy](https://github.com/ni/nilrt/blob/nilrt/master/kirkstone/docs/package-feeds.md#the-extra-feed), extra/ packages are provided as-is.

Further, it looks like the meta-OE layer upstream doesn't have a yocto project bugtracker assigned to it. So they probably default to a policy of requiring downstream dependers to fix their own bugs. So if you want this fixed, you'll have to develop your own patch to meta-OE/master and submit it to the mailing list, per the layer's [README](https://git.openembedded.org/meta-openembedded/tree/meta-oe/README.md).

Hope that helps.
