### ISSUE TITLE
boot option is not changed to LabVIEW RT

### ISSUE THREAD

**Issue by tonycc521** [ni/nilrt#268]
Hello:
I have two questions to ask.
1: boot option is not changed to LabVIEWRT, what should I do?
![DDDd](https://github.com/ni/nilrt/assets/47617106/c4a1221d-8da8-4440-85e2-0cc071fd72b9)

2: Can I install the graphics driver myself?

**Comment by amstewart** [comment]
1. I don't know what you mean. It certainly looks like boot option 1 is `LabVIEW RT`. I'm probably not going to be able to help much regarding bootloading, since that is owned by your board's BIOS.
2. Sure. If you can identify the driver you need, you can install and build it on-target. Or for a production system you can make your own OE layer and add a recipe for that driver.

**Comment by jeminor** [comment]
@tonycc521 :  You appear to be very outside of what we would normally support here.  If you are buying NI products, can you contact your local sales rep and have them explain to us internally what you are doing and how we can best support you?

For now I will close this, please reach out through our sales channels and thanks!
