### ISSUE TITLE
Install Kernel 20.x

### ISSUE THREAD

**Issue by hizlbuzz** [ni/nilrt#63]
For the 19.x Kernel we could install a new Kernel following [this procedure](https://github.com/ni/nilrt/blob/nilrt/19.1/KERNEL_SOURCE.md):

```bash
# copy Kernel/modules/module-versioning-image.squashfs
source /usr/local/natinst/tools/versioning_utils.sh
setup_versioning_env
versioning_call /usr/local/natinst/nikal/bin/updateNIDrivers $(kernel_version)
```

On the 20.x Branches the ` /usr/local/natinst/nikal/bin/updateNIDrivers` is gone. 

What procedure is recommended for the module-versioning ?
With just copying the kernel and modules, I miss the ni-modules. And the Target is not recognized by MAX.

**Comment by amstewart** [comment]
Since the 20.X releases, NI drivers should have switched to using DKMS for module versioning and installation. The `versioning_utils` from that procedure and the legacy "NI-kms" versioning scheme in-general has been deprecated in favor of community tools.

So reversioning the NI drivers atop a custom kernel should be as straightforward as:
1. put the new kernel and kernel-headers on the system
2. make sure `dkms` is installed (it is available in the opkg feeds)
3. rebuild the modules with `dkms autoinstall` and check status with `dkms status`
    * (community documentation for dkms operations should generally hold true for NI LInuxRT as well)

Does that help get you further?

**Comment by hizlbuzz** [comment]
Thank you, `dkms` was the missed piece.


```bash
# copy headers from host
cd /{KernelRoot}/ni-install/x86_64/headers/
unsquashfs module-versioning-image.squashfs
scp -r squashfs-root/kernel/ admin@${TargetIP}:/lib/modules/${KernelVersion}

# on target install proprietary modules
dkms autoinstall
dkms status
```

**Comment by amstewart** [comment]
Glad to hear. I'll go ahead and close this issue and make a note to update that tutorial when we get the opportunity.
