### ISSUE TITLE
GeoLite database unavailable

### ISSUE THREAD

**Issue by bertg42** [ni/nilrt#94]
Bitbake tried to download:
http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
but this no longer exists, so the whole geolite package fails.

**Comment by amstewart** [comment]
I assume you're using one of the sumo branches; right? Seems like the geoip recipe upstream maintainers have [generally had difficulty](https://git.openembedded.org/meta-openembedded/log/meta-networking/recipes-support/geoip) getting stable sources for those binary archives.

Recent versions of the recipe `>geoip_1.6.12` [moved](https://git.openembedded.org/meta-openembedded/commit/meta-networking/recipes-support/geoip?id=3eb2001cdacbf7b6a6d9efdb8c4a8cd9d3e40bf1) those sources to the stable [sources.openembedded.org](http://sources.openembedded.org/) mirror. The solution here is probably just to backport upstream's commits to use sources.openembedded.org. 

@bertg42; assuming that you don't need `geoip` version `1.6.11` specifically, I think you should be able to cherry-pick upstream meta-oe/master's recipe commits and get the fix. You'll want to skip commit [c61dc077bbd81260e4f167fa2251643ba0ba6974](https://git.openembedded.org/meta-openembedded/commit/meta-networking/recipes-support/geoip?id=c61dc077bbd81260e4f167fa2251643ba0ba6974), since the sumo mainline uses the old bitbake overrides syntax.

If you get that working, could you submit a PR against the `nilrt/master/sumo` mainline ref. I'd like to pull it. :)

Otherwise, I'll create an internal item to do it for the next NILRT-sumo release.

**Comment by bertg42** [comment]
@amstewart; Honestly I'm just trying to get some version of this project to compile, I only used sumo because that was the default.  I've encountered lots of little issues, though, and haven't been able to get to an install image yet.  Should I try hardknott?

I don't feel my git-fu is strong enough to try committing any fixes, I'm at the level where I pull stuff and then fiddle until I get it working.  I'm afraid I'd break something for others.

**Comment by amstewart** [comment]
The hardknott mainline is still deep enough in dev that I don't think you'd get much use out of it. The sumo mainline is still current for the next quarter or two. It's unfortunate that external dependencies sometimes break the mainlines, but that's the nature of the beast.

I'll put an item on the team backlog to fix this on our end. Is this blocking anything for you? It may be until after the new year before I can get someone to close on it.

**Comment by amstewart** [comment]
Hmm... seems the `geoip` recipe is a part of the "extras" package feed. Unfortunately, that means that NI doesn't officially support it; so it's going to be difficult for me to argue for it having a high priority on the backlog. On the bright side, it *hopefully* means that it isn't a required package for any of the supported software.

Can you tell me more about what packages/images you're trying to get working? If I understand your use-case, it will be easier for us to prioritize the work.

**Comment by amstewart** [comment]
@bertg42 and I have discussed offline and determined that (a) he doesn't need this recipe for his project and (b) this recipe isn't in the short-list of supported packages from NI. For those reasons, we're closing this issue.
